import { taxonomy } from "./taxonomy.js";

export const fauResources = [
  {
    id: "registrar",
    title: "Registrar",
    category: "Academics",
    subcategory: "Registrar",
    department: "Registrar",
    page_type: "service",
    authority_level: "high",
    retrieval_priority: 10,
    url: "https://www.fau.edu/registrar/",
    description: "Registration, transcripts, enrollment verification, forms, graduation, and student records.",
    keywords: ["register", "transcript", "withdraw", "drop", "graduation", "records", "forms"],
    last_crawled: null,
    document_id: "registrar"
  },
  {
    id: "myfau",
    title: "MyFAU",
    category: "Student Portal",
    subcategory: "Student Portal",
    department: "IT / Student Services",
    page_type: "portal",
    authority_level: "high",
    retrieval_priority: 9,
    url: "https://myfau.fau.edu/",
    description: "FAU student portal for registration, class schedules, account services, email, and student tools.",
    keywords: ["myfau", "portal", "register for classes", "class registration", "student portal", "schedule"],
    last_crawled: null,
    document_id: "myfau"
  },
  {
    id: "academic-calendar",
    title: "Academic Calendar",
    category: "Academics",
    subcategory: "Academic Calendar",
    department: "Registrar",
    page_type: "academic_calendar",
    authority_level: "highest",
    retrieval_priority: 11,
    url: "https://www.fau.edu/registrar/registration/calendar/",
    description: "Important academic dates, deadlines, add/drop windows, final exams, and term schedules.",
    keywords: ["deadline", "calendar", "drop add", "final exams", "semester", "term dates"],
    last_crawled: null,
    document_id: "academic-calendar"
  },
  {
    id: "financial-aid",
    title: "Financial Aid",
    category: "Money",
    subcategory: "Financial Aid",
    department: "Financial Aid",
    page_type: "financial_aid",
    authority_level: "highest",
    retrieval_priority: 10,
    url: "https://www.fau.edu/finaid/",
    description: "FAFSA, grants, scholarships, loans, verification, aid status, and financial aid contacts.",
    keywords: ["fafsa", "scholarship", "loan", "grant", "aid", "verification", "money"],
    last_crawled: null,
    document_id: "financial-aid"
  },
  {
    id: "controller",
    title: "Tuition and Billing",
    category: "Money",
    subcategory: "Tuition & Fees",
    department: "Controller",
    page_type: "tuition",
    authority_level: "highest",
    retrieval_priority: 9,
    url: "https://www.fau.edu/controllers-office/student-services/",
    description: "Tuition payment, billing, refunds, payment deadlines, student accounts, and payment plans.",
    keywords: ["tuition", "bill", "payment", "refund", "account", "fees", "deadline"],
    last_crawled: null,
    document_id: "controller"
  },
  {
    id: "advising",
    title: "University Advising Services",
    category: "Academic Support",
    subcategory: "Academic Advising",
    department: "Advising",
    page_type: "advising",
    authority_level: "high",
    retrieval_priority: 7,
    url: "https://www.fau.edu/uas/",
    description: "Academic advising, appointment guidance, major exploration, course planning, and student support.",
    keywords: ["advisor", "advising", "classes", "major", "appointment", "course plan"],
    last_crawled: null,
    document_id: "advising"
  },
  {
    id: "parking",
    title: "Parking and Transportation",
    category: "Student Life",
    subcategory: "Parking & Transportation",
    department: "Parking",
    page_type: "parking",
    authority_level: "medium",
    retrieval_priority: 5,
    url: "https://www.fau.edu/parking/",
    description: "Parking permits, citations, transportation, shuttles, maps, and campus parking rules.",
    keywords: ["parking", "permit", "citation", "shuttle", "transportation", "car"],
    last_crawled: null,
    document_id: "parking"
  },
  {
    id: "housing",
    title: "Housing and Residential Education",
    category: "Student Life",
    subcategory: "Housing",
    department: "Housing",
    page_type: "housing",
    authority_level: "high",
    retrieval_priority: 6,
    url: "https://www.fau.edu/housing/",
    description: "On-campus housing, residence halls, room selection, move-in, rates, and residential life.",
    keywords: ["housing", "dorm", "residence", "move in", "room", "meal plan"],
    last_crawled: null,
    document_id: "housing"
  },
  {
    id: "canvas",
    title: "Canvas",
    category: "Technology",
    subcategory: "LMS",
    department: "IT",
    page_type: "service",
    authority_level: "high",
    retrieval_priority: 6,
    url: "https://canvas.fau.edu/",
    description: "FAU Canvas login for courses, assignments, grades, announcements, and online class materials.",
    keywords: ["canvas", "assignment", "course", "grades", "online class", "lms"],
    last_crawled: null,
    document_id: "canvas"
  },
  {
    id: "library",
    title: "FAU Libraries",
    category: "Academic Support",
    subcategory: "Libraries",
    department: "Library",
    page_type: "library",
    authority_level: "high",
    retrieval_priority: 6,
    url: "https://www.fau.edu/library/",
    description: "Research databases, study rooms, librarians, books, articles, citations, and library hours.",
    keywords: ["library", "research", "database", "study room", "article", "citation"],
    last_crawled: null,
    document_id: "library"
  },
  {
    id: "career-center",
    title: "Career Center",
    category: "Academic Support",
    subcategory: "Career Center",
    department: "Career Services",
    page_type: "career",
    authority_level: "medium",
    retrieval_priority: 5,
    url: "https://www.fau.edu/career/",
    description: "Resume help, jobs, internships, career fairs, appointments, and interview preparation.",
    keywords: ["career", "resume", "internship", "job", "interview", "handshake"],
    last_crawled: null,
    document_id: "career-center"
  },
  {
    id: "student-health",
    title: "Student Health Services",
    category: "Student Life",
    subcategory: "Student Health",
    department: "Student Health",
    page_type: "health",
    authority_level: "high",
    retrieval_priority: 5,
    url: "https://www.fau.edu/shs/",
    description: "Student health appointments, immunizations, medical forms, insurance, and wellness services.",
    keywords: ["health", "doctor", "immunization", "vaccine", "appointment", "medical"],
    last_crawled: null,
    document_id: "student-health"
  },
  {
    id: "counseling",
    title: "Counseling and Psychological Services",
    category: "Student Life",
    subcategory: "Counseling",
    department: "Counseling",
    page_type: "counseling",
    authority_level: "high",
    retrieval_priority: 5,
    url: "https://www.fau.edu/counseling/",
    description: "Mental health counseling, crisis support, workshops, wellness resources, and appointments.",
    keywords: ["counseling", "mental health", "therapy", "stress", "crisis", "wellness"],
    last_crawled: null,
    document_id: "counseling"
  }
];

// Ensure backwards-compatible fields like `category`, `title`, and `url` remain available.
